defaultPortal: fh-christina
portals:
  - name: fh-christina
    portalId: 443401
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CLXw9JCiMBIIAA0AAAAAAAwYiYgbII7W3wso7ukMMhRFKFIiglgNnSfKzXKTufB4OXidzzooAAAEQQAAAHgAAAAAAAAAAAAAAAAAAAAEAADABwAAAAA8AAAAAAAAYEIUJRjRd2p9ftiutAWcT2lE95HFY85KA25hMVIAWgA
        expiresAt: '2022-07-21T18:55:16.537Z'
    personalAccessKey: >-
      CiQzMTM4YTg3My02MGRlLTQ1ZGQtYWY4Zi05YmYzMDI4YjYxYTQQiYgbGI7W3wsqGQAF5pGCVvqffMaD7GZS5x0bQ4zgbmeYVqpKA25hMQ
