defaultPortal: fh-christina
portals:
  - name: fh-christina
    portalId: 443401
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          COOAo7ijMBIIAA0AAAAAAAwYiYgbII7W3wso7ukMMhQT7L3tq16dTpRIfIRoFQ36bM3KHzooAAAEQQAAAHgAAAAAAAAAAAAAAAAAAAAEAADABwAAAAA8AAAAAAAAYEIUNFlHdSipHt12JQpZQ9GTxDyhzM5KA25hMVIAWgA
        expiresAt: '2022-07-25T20:24:56.678Z'
    personalAccessKey: >-
      CiQzMTM4YTg3My02MGRlLTQ1ZGQtYWY4Zi05YmYzMDI4YjYxYTQQiYgbGI7W3wsqGQAF5pGCVvqffMaD7GZS5x0bQ4zgbmeYVqpKA25hMQ
