defaultPortal: fh-christina
portals:
  - name: fh-christina
    portalId: 443401
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CNym_5WgMBIIAA0AAAAAAAwYiYgbII7W3wso7ukMMhTeiS1hVpB9CKoofyI_Fx7Hi4M7eTooAAAEQQAAAHgAAAAAAAAAAAAAAAAAAAAEAADABwAAAAA8AAAAAAAAYEIUgwUqI6Y-mU47S--QiwIZr7RKOfZKA25hMVIAWgA
        expiresAt: '2022-07-15T16:45:02.176Z'
    personalAccessKey: >-
      CiQzMTM4YTg3My02MGRlLTQ1ZGQtYWY4Zi05YmYzMDI4YjYxYTQQiYgbGI7W3wsqGQAF5pGCVvqffMaD7GZS5x0bQ4zgbmeYVqpKA25hMQ
