defaultPortal: fh-christina
portals:
  - name: fh-christina
    portalId: 443401
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CNS3svmdMBIIAA0AAAAAAAwYiYgbII7W3wso7ukMMhQ8p9qvUUUcP7m_FWKMDLCJ8PY7uDooAAAEQQAAAHgAAAAAAAAAAAAAAAAAAAAEAADABwAAAAA8AAAAAAAAYEIUafKaeAICRZJw8F_489N8t0ywqVdKA25hMVIAWgA
        expiresAt: '2022-07-08T18:57:31.608Z'
    personalAccessKey: >-
      CiQzMTM4YTg3My02MGRlLTQ1ZGQtYWY4Zi05YmYzMDI4YjYxYTQQiYgbGI7W3wsqGQAF5pGCVvqffMaD7GZS5x0bQ4zgbmeYVqpKA25hMQ
