defaultPortal: fh-christina
portals:
  - name: fh-christina
    portalId: 443401
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CM-Gv_eLMBIIAA0AAAAAAAwYiYgbII7W3wso7ukMMhS5Ygb-nsMvDsS9v7Zi4gcP3PRwqTooAAAEQQAAAHgAAAAAAAAAAAAAAAAAAAAEAADABwAAAAA8AAAAAAAAYEIU_5vmzWEgUY5ozQjyLcMDWShp5UlKA25hMVIAWgA
        expiresAt: '2022-05-13T19:40:25.812Z'
    personalAccessKey: >-
      CiQzMTM4YTg3My02MGRlLTQ1ZGQtYWY4Zi05YmYzMDI4YjYxYTQQiYgbGI7W3wsqGQAF5pGCVvqffMaD7GZS5x0bQ4zgbmeYVqpKA25hMQ
