defaultPortal: fh-christina
portals:
  - name: fh-christina
    portalId: 443401
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CLHl3qKfMBIIAA0AAAAAAAwYiYgbII7W3wso7ukMMhTrOQ-CV3BylimNlAR4Jfx18Pgd6jooAAAEQQAAAHgAAAAAAAAAAAAAAAAAAAAEAADABwAAAAA8AAAAAAAAYEIU8yQj9HqO6Mn496fYCcO1aUDAf9FKA25hMVIAWgA
        expiresAt: '2022-07-12T21:36:37.046Z'
    personalAccessKey: >-
      CiQzMTM4YTg3My02MGRlLTQ1ZGQtYWY4Zi05YmYzMDI4YjYxYTQQiYgbGI7W3wsqGQAF5pGCVvqffMaD7GZS5x0bQ4zgbmeYVqpKA25hMQ
