defaultPortal: fh-christina
portals:
  - name: fh-christina
    portalId: 443401
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CN-VoM2dMBIIAA0AAAAAAAwYiYgbII7W3wso7ukMMhR9SWHlMvklT0uh3Qck6UIgBoFDATooAAAEQQAAAHgAAAAAAAAAAAAAAAAAAAAEAADABwAAAAA8AAAAAAAAYEIUihw2CBpCKmU6PQaHMWWZBrum68RKA25hMVIAWgA
        expiresAt: '2022-07-07T17:14:37.667Z'
    personalAccessKey: >-
      CiQzMTM4YTg3My02MGRlLTQ1ZGQtYWY4Zi05YmYzMDI4YjYxYTQQiYgbGI7W3wsqGQAF5pGCVvqffMaD7GZS5x0bQ4zgbmeYVqpKA25hMQ
