defaultPortal: fh-christina
portals:
  - name: fh-christina
    portalId: 443401
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CLzoq5-fMBIIAA0AAAAAAAwYiYgbII7W3wso7ukMMhR_SQPTPhJFkC_Tgx9SivvrLBeBazooAAAEQQAAAHgAAAAAAAAAAAAAAAAAAAAEAADABwAAAAA8AAAAAAAAYEIUarFwJj5UAy_Bl8zJH142fiAMfsVKA25hMVIAWgA
        expiresAt: '2022-07-12T19:37:50.401Z'
    personalAccessKey: >-
      CiQzMTM4YTg3My02MGRlLTQ1ZGQtYWY4Zi05YmYzMDI4YjYxYTQQiYgbGI7W3wsqGQAF5pGCVvqffMaD7GZS5x0bQ4zgbmeYVqpKA25hMQ
