defaultPortal: fh-christina
portals:
  - name: fh-christina
    portalId: 443401
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CKa_z7ehMBIIAA0AAAAAAAwYiYgbII7W3wso7ukMMhSvFCDUKNWQCZWqWR3FYgINodaRODooAAAEQQAAAHgAAAAAAAAAAAAAAAAAAAAEAADABwAAAAA8AAAAAAAAYEIU06eAhO61mYL1G02u1CeJaxj6yFNKA25hMVIAWgA
        expiresAt: '2022-07-19T14:54:17.515Z'
    personalAccessKey: >-
      CiQzMTM4YTg3My02MGRlLTQ1ZGQtYWY4Zi05YmYzMDI4YjYxYTQQiYgbGI7W3wsqGQAF5pGCVvqffMaD7GZS5x0bQ4zgbmeYVqpKA25hMQ
