defaultPortal: fh-christina
portals:
  - name: fh-christina
    portalId: 443401
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CPzs0bObMBIIAA0AAAAAAAwYiYgbII7W3wso7ukMMhSuVl1TNJYLaTlYcfKi-SkAiY8xZzooAAAEQQAAAHgAAAAAAAAAAAAAAAAAAAAEAADABwAAAAA8AAAAAAAAYEIU2Kr__VBAV9SJ6N-GPSEh5E12Lr9KA25hMVIAWgA
        expiresAt: '2022-06-30T21:11:34.785Z'
    personalAccessKey: >-
      CiQzMTM4YTg3My02MGRlLTQ1ZGQtYWY4Zi05YmYzMDI4YjYxYTQQiYgbGI7W3wsqGQAF5pGCVvqffMaD7GZS5x0bQ4zgbmeYVqpKA25hMQ
