defaultPortal: fh-christina
portals:
  - name: fh-christina
    portalId: 443401
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CLWHp6udMBIIAA0AAAAAAAwYiYgbII7W3wso7ukMMhSYcP7YnhremLJdT9khyFALrVJLcjooAAAEQQAAAHgAAAAAAAAAAAAAAAAAAAAEAADABwAAAAA8AAAAAAAAYEIUeK0axO9YQc6jZB4I626KQ0Qj-CpKA25hMVIAWgA
        expiresAt: '2022-07-06T21:28:07.353Z'
    personalAccessKey: >-
      CiQzMTM4YTg3My02MGRlLTQ1ZGQtYWY4Zi05YmYzMDI4YjYxYTQQiYgbGI7W3wsqGQAF5pGCVvqffMaD7GZS5x0bQ4zgbmeYVqpKA25hMQ
