defaultPortal: fh-christina
portals:
  - name: fh-christina
    portalId: 443401
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          COKssZihMBIIAA0AAAAAAAwYiYgbII7W3wso7ukMMhSLRprpACiHUZ80pMUZqq__5Qb3HzooAAAEQQAAAHgAAAAAAAAAAAAAAAAAAAAEAADABwAAAAA8AAAAAAAAYEIUqRPiGS8oqh2IPTpq9B5Yn7CDKuhKA25hMVIAWgA
        expiresAt: '2022-07-18T20:42:31.909Z'
    personalAccessKey: >-
      CiQzMTM4YTg3My02MGRlLTQ1ZGQtYWY4Zi05YmYzMDI4YjYxYTQQiYgbGI7W3wsqGQAF5pGCVvqffMaD7GZS5x0bQ4zgbmeYVqpKA25hMQ
