defaultPortal: fh-christina
portals:
  - name: fh-christina
    portalId: 443401
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CMeKw8ydMBIIAA0AAAAAAAwYiYgbII7W3wso7ukMMhQRR-Aj8vz-nlYbrFODSosATGU0FjooAAAEQQAAAHgAAAAAAAAAAAAAAAAAAAAEAADABwAAAAA8AAAAAAAAYEIU372vzIZt2KPUPwOabGlRX0NRU1lKA25hMVIAWgA
        expiresAt: '2022-07-07T16:49:12.522Z'
    personalAccessKey: >-
      CiQzMTM4YTg3My02MGRlLTQ1ZGQtYWY4Zi05YmYzMDI4YjYxYTQQiYgbGI7W3wsqGQAF5pGCVvqffMaD7GZS5x0bQ4zgbmeYVqpKA25hMQ
