defaultPortal: fh-christina
portals:
  - name: fh-christina
    portalId: 443401
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CPHEt_2dMBIIAA0AAAAAAAwYiYgbII7W3wso7ukMMhSYhysiUO-T50xqxJVcgr9UB_05mTooAAAEQQAAAHgAAAAAAAAAAAAAAAAAAAAEAADABwAAAAA8AAAAAAAAYEIUGaB5beEedsD1mOmBSeQDWsysmntKA25hMVIAWgA
        expiresAt: '2022-07-08T21:18:43.830Z'
    personalAccessKey: >-
      CiQzMTM4YTg3My02MGRlLTQ1ZGQtYWY4Zi05YmYzMDI4YjYxYTQQiYgbGI7W3wsqGQAF5pGCVvqffMaD7GZS5x0bQ4zgbmeYVqpKA25hMQ
