defaultPortal: fh-christina
portals:
  - name: fh-christina
    portalId: 443401
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CI7U77qhMBIIAA0AAAAAAAwYiYgbII7W3wso7ukMMhSTLrrvEinjGPtLnpTrW0LEhTc5aTooAAAEQQAAAHgAAAAAAAAAAAAAAAAAAAAEAADABwAAAAA8AAAAAAAAYEIU9P3IrqzBGUVUFTd1j9PrwUqqBPlKA25hMVIAWgA
        expiresAt: '2022-07-19T16:47:55.922Z'
    personalAccessKey: >-
      CiQzMTM4YTg3My02MGRlLTQ1ZGQtYWY4Zi05YmYzMDI4YjYxYTQQiYgbGI7W3wsqGQAF5pGCVvqffMaD7GZS5x0bQ4zgbmeYVqpKA25hMQ
