defaultPortal: fh-christina
portals:
  - name: fh-christina
    portalId: 443401
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CIiq3pifMBIIAA0AAAAAAAwYiYgbII7W3wso7ukMMhSERZ22n_OWQjiuvkRgkZWBJaSPxzooAAAEQQAAAHgAAAAAAAAAAAAAAAAAAAAEAADABwAAAAA8AAAAAAAAYEIU5pwheSqLQyTvsnhYR6rr7ax_WJJKA25hMVIAWgA
        expiresAt: '2022-07-12T15:46:57.937Z'
    personalAccessKey: >-
      CiQzMTM4YTg3My02MGRlLTQ1ZGQtYWY4Zi05YmYzMDI4YjYxYTQQiYgbGI7W3wsqGQAF5pGCVvqffMaD7GZS5x0bQ4zgbmeYVqpKA25hMQ
