defaultPortal: fh-christina
portals:
  - name: fh-christina
    portalId: 443401
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CLi2g5CiMBIIAA0AAAAAAAwYiYgbII7W3wso7ukMMhQ1yCew6QZA8HxFY8cdGp7DtUCCVDooAAAEQQAAAHgAAAAAAAAAAAAAAAAAAAAEAADABwAAAAA8AAAAAAAAYEIUbIswRHu_aSQZIR1zneP8kEyzV1hKA25hMVIAWgA
        expiresAt: '2022-07-21T18:24:17.724Z'
    personalAccessKey: >-
      CiQzMTM4YTg3My02MGRlLTQ1ZGQtYWY4Zi05YmYzMDI4YjYxYTQQiYgbGI7W3wsqGQAF5pGCVvqffMaD7GZS5x0bQ4zgbmeYVqpKA25hMQ
