defaultPortal: fh-christina
portals:
  - name: fh-christina
    portalId: 443401
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CJPfsLyiMBIIAA0AAAAAAAwYiYgbII7W3wso7ukMMhR1RaoCZZ6RGImlIpqUGHkuyrOVrDooAAAEQQAAAHgAAAAAAAAAAAAAAAAAAAAEAADABwAAAAA8AAAAAAAAYEIUxcvYc4RlBKenmAm0trLIJ8A-Vp1KA25hMVIAWgA
        expiresAt: '2022-07-22T20:14:34.903Z'
    personalAccessKey: >-
      CiQzMTM4YTg3My02MGRlLTQ1ZGQtYWY4Zi05YmYzMDI4YjYxYTQQiYgbGI7W3wsqGQAF5pGCVvqffMaD7GZS5x0bQ4zgbmeYVqpKA25hMQ
