defaultPortal: fh-christina
portals:
  - name: fh-christina
    portalId: 443401
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CM-Tw6idMBIIAA0AAAAAAAwYiYgbII7W3wso7ukMMhSV1H9ob735KCyQLGdbNy38dAnxmzooAAAEQQAAAHgAAAAAAAAAAAAAAAAAAAAEAADABwAAAAA8AAAAAAAAYEIUWCpkfg3je67Gcayr6V0HQZC8JeFKA25hMVIAWgA
        expiresAt: '2022-07-06T19:50:56.212Z'
    personalAccessKey: >-
      CiQzMTM4YTg3My02MGRlLTQ1ZGQtYWY4Zi05YmYzMDI4YjYxYTQQiYgbGI7W3wsqGQAF5pGCVvqffMaD7GZS5x0bQ4zgbmeYVqpKA25hMQ
