defaultPortal: fh-christina
portals:
  - name: fh-christina
    portalId: 443401
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CNXFrpmhMBIIAA0AAAAAAAwYiYgbII7W3wso7ukMMhRQghqCKKoDIF2AH8Ev03TUup1OdTooAAAEQQAAAHgAAAAAAAAAAAAAAAAAAAAEAADABwAAAAA8AAAAAAAAYEIULdgoggcdiNxYG-WKVTAIm4iFAixKA25hMVIAWgA
        expiresAt: '2022-07-18T21:16:43.096Z'
    personalAccessKey: >-
      CiQzMTM4YTg3My02MGRlLTQ1ZGQtYWY4Zi05YmYzMDI4YjYxYTQQiYgbGI7W3wsqGQAF5pGCVvqffMaD7GZS5x0bQ4zgbmeYVqpKA25hMQ
