defaultPortal: fh-christina
portals:
  - name: fh-christina
    portalId: 443401
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CIr6ovafMBIIAA0AAAAAAAwYiYgbII7W3wso7ukMMhT5KpeAAwC_xSvfnWZsHX0lHe3OxTooAAAEQQAAAHgAAAAAAAAAAAAAAAAAAAAEAADABwAAAAA8AAAAAAAAYEIUQVEFm8AN_jtBCsUqa6yUNe7Cf7RKA25hMVIAWgA
        expiresAt: '2022-07-14T22:16:17.421Z'
    personalAccessKey: >-
      CiQzMTM4YTg3My02MGRlLTQ1ZGQtYWY4Zi05YmYzMDI4YjYxYTQQiYgbGI7W3wsqGQAF5pGCVvqffMaD7GZS5x0bQ4zgbmeYVqpKA25hMQ
