defaultPortal: fh-christina
portals:
  - name: fh-christina
    portalId: 443401
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CPvIuZ6fMBIIAA0AAAAAAAwYiYgbII7W3wso7ukMMhS-btFqVJw0EtkWd4JbG6SqHqV0JzooAAAEQQAAAHgAAAAAAAAAAAAAAAAAAAAEAADABwAAAAA8AAAAAAAAYEIU_b4ZoCgICtBRpILtmiC2x7fYsTNKA25hMVIAWgA
        expiresAt: '2022-07-12T19:06:38.592Z'
    personalAccessKey: >-
      CiQzMTM4YTg3My02MGRlLTQ1ZGQtYWY4Zi05YmYzMDI4YjYxYTQQiYgbGI7W3wsqGQAF5pGCVvqffMaD7GZS5x0bQ4zgbmeYVqpKA25hMQ
